### PR TITLE
Fix mapFileCommentRegex to match mapping file URL with query.

### LINKED ISSUE #52: source-map file name with query parameter, causes source-map not found
In the javascript file, if `sourceMappingURL` file name has parameter, like:

```javascript
//# sourceMappingURL=foo.min.js.map?hashcode
```
the converter can't find the source map file
https://github.com/danvk/source-map-explorer/issues/46

### PR DESCRIPTION
**Pull request by UncleBill**
Fixed #52 . And add a test.
All test passed!

### CODE REVIEW

**Comment by thlorenz** [comment]
LGTM @lydell you wanna have a look and let us know if the fix is valid?


Also @UncleBill made you collaborator.

Once we get @lydell's feedback, please merge to master following [this guide](https://gist.github.com/thlorenz/f7df0daf13c6f6c1fa84).
I will then version and publish to npm.

Thanks.

**Comment by lydell** [comment]
So ... the capturing groups of the regex extract the URL of the sourceMappingURL comment, right? But now it has been changed to capture the URL except the query string? Feels pretty arbitrary to me. The query string could be needed when asking a web server for the source map. Isn't it up to the code that _uses_ this regex to deal with query parameters? Remember, it is a _URL_ so one can't just give it to `fs.readFileSync` directly. ¯\\\_(ツ)\_/¯

**Comment by UncleBill** [comment]
@lydell I did write a version of patch removing query from the URL before `fs.readFileSync`.

```diff
diff --git a/index.js b/index.js
index cf0e81f..daa6442 100644
--- a/index.js
+++ b/index.js
@@ -32,6 +32,11 @@ function readFromFileMap(sm, dir) {

   // for some odd reason //# .. captures in 1 and /* .. */ in 2
   var filename = r[1] || r[2];
+  // remove query of the mapping URL
+  if (filename.indexOf('?') > -1) {
+    // It's safe to remove, since `?` is not allowed inside a filename/filepath.
+    filename = filename.replace(/\?.*$/, '')
+  }
   var filepath = path.resolve(dir, filename);

   try {
```

>The query string could be needed when asking a web server for the source map.

This sounds making sense. What do you think? @thlorenz

**Comment by UncleBill** [comment]
@thlorenz I pushed a new commit. You can cherry-pick the first commit, or squash the two into a single one before merging.

**Comment by thlorenz** [comment]
@UncleBill @lydell did we have a test for the readFileSync case?
I wanna make sure we don't break anything.

Ideally we'd add that test _before_ these changes and make sure it passes before applying them as well as after.
Adding this test would speed up merging this PR as then I can trust nothing broke instead of having to do a much more careful review (for which I may only have time in a few days).
Thanks.

**Comment by thlorenz** [comment]
Closing since this is old and I haven't heard back WRT tests.

**Pull request closed without merging**
