### PR TITLE
Altered commentRx to avoid a RangeError under certain conditions in io.js.

### PR DESCRIPTION
**Pull request by greim**
Regex taken from here https://github.com/thlorenz/convert-source-map/pull/10/files and then altered slightly to avoid the error I was having.

### CODE REVIEW

**Comment by greim** [comment]
`npm test` still passes for me also.

**Comment by thlorenz** [comment]
Thanks, published as 0.5.

Would you mind to apply a similar change to the mapFileRegex?
Also please use `\s` for whitespace and add possibility of `charset:...` to be present in the regex, [like I did here](https://github.com/thlorenz/convert-source-map/commit/89ebf1288a9741189bf4d4c3ac6a1deca42a43d6#diff-168726dbe96b3ce427e7fedce31bb0bcR5)

As a bonus you could add tests [similar to those](https://github.com/thlorenz/convert-source-map/commit/89ebf1288a9741189bf4d4c3ac6a1deca42a43d6#diff-6f3549cb1f1eaa78a756a08fb5cddf26R16) for mapFileRegex to ensure it matches with charset as well.

I know you don't personally need that feature, but at this point both regexes are inconsistent.

BTW publishes as minor upgrade since the regexes are part of API, so please bug authors to upgrade convert-source-map in their packages.

**Comment by greim** [comment]
I see that `..*` got changed to `.*`, was that intentional?

**Comment by greim** [comment]
Also see: https://github.com/thlorenz/convert-source-map/issues/9#issuecomment-75119049

**Comment by greim** [comment]
Also, I'm unable to re-open this. Should I create a new PR?

**Comment by thlorenz** [comment]
Yes it was intentional it's the same thing (except it doesn't force anything to be there. We could change to `.+` if that was wrong)

And yes if you want to do the change I suggested please open a new PR.

**Comment by greim** [comment]
Haha, well, `.+` is what was apparently breaking in my environment in the first place. (Which is weird since `..*` and `.+` are basically equivalent). I think I'll just have it use `.*` in both the regexes for consistency, assuming it passes the tests.

**Pull request closed without merging**
