### PR TITLE
Don't match mapFileCommentRx inside strings

### PR DESCRIPTION
**Pull request by zertosh**
Alternate proposal to https://github.com/thlorenz/convert-source-map/pull/27

### CODE REVIEW

**Comment by thlorenz** [comment]
Could you please explain how the results are different here?
Thanks.

**Comment by zertosh** [comment]
The previous url capture group ( `(.+?)`) grabbed anything. Since urls can't have quotes,  `([^\s'"]+?)` can be used instead. This solves the problem of mistaken source map annotations in strings.

It's not necessary to change the regex segment for `/* sourceMappingURL=.... */` because that one makes sure that the annotation ends in `*/`.

Looking at the test diff for L86-88 and L105-107, those assertions would fail in the unpatched version. The rest of the diff is comments and refactoring to use `mapFileCommentWrap`.

**Comment by thlorenz** [comment]
Merged and published as `1.1.1`, so is a patch that will be picked up automatically when people reinstall browserify.
Thanks.

**Comment by zertosh** [comment]
Thank you!

**Pull request closed without merging**
