### PR TITLE
Altered commentRx to avoid a RangeError under certain conditions in io.js (this time with better regexes).

### PR DESCRIPTION
**Pull request by greim**
Incorporates some of the changes discussed here: https://github.com/thlorenz/convert-source-map/pull/11#issuecomment-75067442

### CODE REVIEW

**Comment by thlorenz** [comment]
Could you please rebase this on master and squash into one commit?
Thanks.

**Comment by thlorenz** [comment]
Any news on this? I believe with the latest patch we touched a regex but not the one you changed, so it should still be easy to rebase this.

**Comment by greim** [comment]
Okay. Rebased on master, fixed a conflict, had to type `git rebase --skip`, then squash merged all of that back to master. All to fix a regex. But now it's not on this branch anymore. Want me to make a new PR?

**Comment by thlorenz** [comment]
Yes you can just create a new PR. We can review there what you did and pull it in if all is well.

> All to fix a regex

Don't belittle that, optimizing the regex makes a huge difference, so I thank you for taking the time and doing so.
If you think about it this entire module is mainly a glorified wrapper around using that regex ;)

**Comment by greim** [comment]
Closing in favor of a simpler PR.

**Comment by dmitry** [comment]
@greim what was that?

**Comment by greim** [comment]
The essence of the fix had been changing `.+` to `..*` in a regex. My guess was it was triggering an arcane v8 bug which only happened in very specific circumstances. I eventually just re-ordered some adjacent-but-unrelated gulp tasks and the problem went away :)

**Comment by dmitry** [comment]
@greim thanks for the response! I've similarly fixed an issue: https://github.com/demerzel3/karma-sourcemap-loader/pull/18 

In my case it happened on every second pass to match the string, I believe it's somehow related to the V8 regex optimizations.

**Pull request closed without merging**
