### PR TITLE
Make the readme example more sensible

### PR DESCRIPTION
**Pull request by lydell**
Previously, "sources" and "sourcesContent" were mixed up.

### CODE REVIEW

**Comment by amilajack** [comment]
Makes sense. @thlorenz Thoughts?

**Comment by thlorenz** [comment]
No it doesn't, sorry.
`sources` are actually the source of the code, not a filename.

So unless I'm missing something here I wouldn't like to merge this.

**Comment by lydell** [comment]
@thlorenz Quoting the [spec](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit#heading=h.qz3o9nc69um5):

> ### Proposed Format

> ```
> 1. {
> 2. "version" : 3,
> 3. "file": "out.js",
> 4. "sourceRoot": "",
> 5. "sources": ["foo.js", "bar.js"],
> 6. "sourcesContent": [null, null],
> 7. "names": ["src", "maps", "are", "fun"],
> 8. "mappings": "A,AAAB;;ABCDE;"
> 9. }
> ```
>
> Line 1: The entire file is a single JSON object
> ...
> Line 5: A list of original sources used by the “mappings” entry.
> Line 6: An optional list of source content, useful when the “source” can’t be hosted. The contents are listed in the same order as the sources in line 5. “null” may be used if some original sources should be retrieved by name.

:wink:

**Comment by thlorenz** [comment]
ah ok looks like I there is some confusion regarding sources and sourcesContent for a second there.

However when running the example in this repo I get:

```
> node example/comment-to-json.js
{"version":3,"file":"foo.js","sources":["console.log(\"hi\");"],"names":[],"mappings":"AAAA","sourceRoot":"/"}
{"version":3,"file":"foo.js","sources":["CONSOLE.LOG(\"HI\");"],"names":[],"mappings":"AAAA","sourceRoot":"/"}
```

so wouldn't want to show conflicting output in the Readme.

As you can see that conflicts with the proposal you linked, but we need to show what this module is actually doing.

**Comment by lydell** [comment]
Ah, I didn't now that the example in the readme came from example/comment-to-json.js! Thanks for pointing that out. I've updated that example now.

**Comment by lydell** [comment]
- Open a source map from any project you work on and check "sources" vs. "sourcesContent" in it.
- See this [test case](https://github.com/mozilla/source-map/blob/95a3c3b375e2aa9f03843ba6d74fe4f427e77b5c/test/util.js#L161-L176) in the mozilla/source-map module.
- It's called sources<strong>Content</strong> because it contains the _contents_ of the files listed in "sources".

**Comment by thlorenz** [comment]
@lydell so the example was wrong all along?
The module itself works correctly though afaik.

Thanks for catching my mistake.

If so please squash both commits into one. 
I also made you collaborator.

So after squashing please merge to master following [this guide](https://gist.github.com/thlorenz/f7df0daf13c6f6c1fa84).

Probably we won't need to republish to npm as none of the actual behavior changed.

Thanks.

**Comment by lydell** [comment]
Yes, the example was "wrong" all along. "Wrong" in the sense that it was misleading/confusing, but technically correct ("sources" was an array of strings as expected, just with unexpected contents of those strings).

So, yes, the module itself works correctly, and no npm republish should be needed (unless you want the https://www.npmjs.com/package/convert-source-map page to contain the updated example).

I've squashed the commits now.

Thank you for your time! :+1:

**Comment by lydell** [comment]
@thlorenz I don't seem to have become a collaborator, which is why I havent' merged yet :)

**Comment by thlorenz** [comment]
OK, added you. Please squash all commits into one before merging to master.

**Comment by thlorenz** [comment]
Also could you please remove the Bitdeli badge at the bottom? Not working anymore anyhow.

**Comment by lydell** [comment]
Huh?

**Comment by thlorenz** [comment]
Don't worry about it @lydell but at the bottom of the README there is a link to the Bitdeli badge and I don't need it anymore.

**Pull request closed without merging**
