### PR TITLE
Altered commentRx to avoid a RangeError under certain conditions in io.js.

### PR DESCRIPTION
**Pull request by greim**

### CODE REVIEW

**Comment by thlorenz** [comment]
LGTM, but two things:

- could you please properly rebase this on master so that I see one commit with just the one line change (if that is a problem I can just cherry-pick  0c5fdff onto master)
- since now we have an [alternate way]() to deal with the `stack exceeded` issue what are the added benefits from this?

I myself think that of course it's better to not run into that error even when using the regex algorithm however I just want to get your opinion on how this affects how strict this regex is.
I.e. are we gonna have more matches that aren't a source map?

Also is there any speed improvement/decrease you're aware of after changing the regex?

**Comment by greim** [comment]
My original fix involved changing `.+` to `..*` in the regex. I'd honestly be inclined to abandon this PR and create a new one scoped down to just that one minimal change. Those two expressions mean the same thing so it shouldn't change program behavior at all, other than avoiding the range error. Any other regex cleanup could go into other commits. What do you think?

**Comment by thlorenz** [comment]
>  I'd honestly be inclined to abandon this PR and create a new one scoped down to just that one minimal change

I'd love that. You can just create a fresh PR - don't worry about rebasing I'll just cherry-pick your commit.

**Comment by greim** [comment]
Will do. Closing this...

**Comment by greim** [comment]
Hmm, actually the specific change I'm interested in looks like it made it in already. https://github.com/thlorenz/convert-source-map/blob/master/index.js#L5 https://github.com/thlorenz/convert-source-map/commit/aa7ed4f423a95e973d8c3838226638c87ced1d77

I'll refrain from adding a PR and update my project to use this; hopefully it will work :)

**Comment by thlorenz** [comment]
Cool, thanks and sorry for the runaround you experienced. Comes with Open Source :)

**Pull request closed without merging**
