### PR TITLE
Added travis ci support for modern node versions

### PR DESCRIPTION
**Pull request by amilajack**

### CODE REVIEW

**Comment by thlorenz** [comment]
Thanks, I'd like to keep testing on 0.10 and add 0.12 as well.

**Comment by amilajack** [comment]
Fixed

**Comment by thlorenz** [comment]
amilajack made you collaborator.

Please merge to master following [this guide](https://gist.github.com/thlorenz/f7df0daf13c6f6c1fa84).
I will then version and publish to npm.

Thanks.

**Comment by thlorenz** [comment]
May have been superseeded by #51 which included travis updates.

Anything else from here that you need?

**Comment by amilajack** [comment]
Not really. The repo is fine now :)

**Pull request closed without merging**
