### PR TITLE
add getCommentValue and getMapFileCommentValue methods

### PR DESCRIPTION
**Pull request by phated**
@thlorenz I'm finding the need for these methods in some code I'm writing.  I was trying to do the regexp dance in my code but found that `commentRegex` didn't have a capture group so I figured it'd be nice to just have the APIs built-in while I was making that change.  I'm open to changing the method names, but couldn't think of a more descriptive name.

Thoughts?

### CODE REVIEW

**Comment by phated** [comment]
Just realized that one of the new methods could be used internally. Updated PR.

**Comment by thlorenz** [comment]
Looks good, just concerned with perf overhead when we capture especially for large files.
Do you have any data there?
I'm concerned with two things:

1) it getting a lot slower due to capturing
2) regexing is done recursively internally and in the past we ran into cases where v8 would blow the stack, so I'm wondering if capturing causes more recursion (don't have enough knowledge of inner v8 workings to make a call here)

**Comment by phated** [comment]
I'll try to dig into those things.  Currently writing test for my library with these changes linked in, so I'll do some experimenting.

**Comment by phated** [comment]
Didn't get a chance to dig into blowing the stack but calling it a day.  Putting this here for future reference: https://bugs.chromium.org/p/v8/issues/detail?id=3878

**Comment by thlorenz** [comment]
Sounds good, gonna wait with the merge until you finished experimenting so we have a better idea of the impact of the capture.

**Comment by thlorenz** [comment]
Closing due to long inactivity.

**Comment by phated** [comment]
Hey @thlorenz - good to see you back! I think this will still be an issue for me once I continue work on gulp stuff (trying to get some funding going right now). How would you want me to proceed at that point??

**Comment by thlorenz** [comment]
Well we left it at you coming back after experimenting :P 
So we can pick it up there. Basically I'm open to add/change anything as long as it doesn't break functionality nor affects perf negatively ...
Maybe once you have suggestions with what you need just file a new PR .. unless you wanna go with this one .. I can reopen if needed.

**Pull request closed without merging**
