### PR TITLE
Chore: reduce package size.

### PR DESCRIPTION
**Pull request by evilebottnawi**
Ref: https://github.com/thlorenz/convert-source-map/issues/54

### CODE REVIEW

**Comment by thlorenz** [comment]
Thanks, waiting for #55 to get sorted out and will publish a new version then.

Also made you collaborator.

So in the future after enough of us agree with a PR, you can merge to master yourself following [this guide](https://gist.github.com/thlorenz/f7df0daf13c6f6c1fa84).
I will then version and publish to npm.

Thanks.

**Comment by evilebottnawi** [comment]
@thlorenz Thank! :+1:

**Comment by phated** [comment]
FYI the LICENSE file will also be picked up in the publish (npm merges it with `files`).  I usually put it in `files` to be explicit, you never know when they will change behavior.

**Comment by evilebottnawi** [comment]
@phated i don't think that this behavior will change, it never happened :smile:

**Comment by thlorenz** [comment]
OK, for me either way works. Thanks for pointing it out @phated.
If anyone wants to add it I'm fine, but not worried with the way things work ATM either.

**Comment by phated** [comment]
Same, just wanted to post for posterity.  If I remember to toss it into a commit, I'll add it to the array.

**Pull request merged**
